import { pool, withTransaction } from './db.js';

function normalizeProposal(input) {
  const p = input || {};
  if (!String(p.clientName || '').trim()) throw Object.assign(new Error('Client name is required.'), { status: 400 });
  return { clientName:String(p.clientName).trim(), budget:Math.max(0,Number(p.budget)||0), teamSize:Math.max(1,Number(p.teamSize ?? p.plannedTeamSize)||1), startDate:p.startDate||null, endDate:p.endDate||null, relationship:p.relationship==='existing'?'existing':'new', request:String(p.request||''), backendStory:String(p.backendStory||''), status:p.status==='generated'?'generated':'draft', selectedStack:[...new Set((p.selectedStack||[]).map(item=>String(item).trim()).filter(item=>item.length>0&&item.length<=80))], modules:Array.isArray(p.modules)?p.modules:[], roles:p.roles||{} };
}
async function replaceChildren(client,id,data) {
  await client.query('DELETE FROM proposal_technologies WHERE proposal_id=$1',[id]); await client.query('DELETE FROM proposal_modules WHERE proposal_id=$1',[id]); await client.query('DELETE FROM proposal_roles WHERE proposal_id=$1',[id]);
  for(const technology of data.selectedStack) await client.query('INSERT INTO proposal_technologies(proposal_id,technology) VALUES($1,$2)',[id,technology]);
  for(const [index,m] of data.modules.entries()) await client.query('INSERT INTO proposal_modules(proposal_id,title,module_type,story_points,development_people,qa_people,performance_people,estimated_weeks,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,m.name||m.title||'Untitled module',m.type||m.moduleType||'Build',Math.max(1,Number(m.points||m.storyPoints||1)),Math.max(0,Number(m.dev||m.developmentPeople||0)),Math.max(0,Number(m.qa||m.qaPeople||0)),Math.max(0,Number(m.perf||m.performancePeople||0)),Math.max(1,Number(m.estimatedWeeks||1)),index]);
  for(const [role,count] of Object.entries(data.roles)) await client.query('INSERT INTO proposal_roles(proposal_id,role_name,people_count) VALUES($1,$2,$3)',[id,role,Math.max(0,Number(count||0))]);
}
export async function getProposal(client,id,userId) {
  const proposal=(await client.query('SELECT * FROM proposals WHERE id=$1 AND user_id=$2',[id,userId])).rows[0]; if(!proposal)return null;
  const [stack,modules,roles,attachments]=await Promise.all([client.query('SELECT technology FROM proposal_technologies WHERE proposal_id=$1 ORDER BY technology',[id]),client.query('SELECT * FROM proposal_modules WHERE proposal_id=$1 ORDER BY sort_order',[id]),client.query('SELECT role_name,people_count FROM proposal_roles WHERE proposal_id=$1 ORDER BY role_name',[id]),client.query('SELECT id,original_name,mime_type,size_bytes,uploaded_at FROM proposal_attachments WHERE proposal_id=$1 ORDER BY uploaded_at DESC',[id])]);
  return {id:proposal.id,clientName:proposal.client_name,budget:Number(proposal.budget),teamSize:proposal.planned_team_size,startDate:proposal.start_date,endDate:proposal.end_date,relationship:proposal.client_relationship,request:proposal.proposal_request,backendStory:proposal.backend_story,status:proposal.status,selectedStack:stack.rows.map(row=>row.technology),modules:modules.rows.map(m=>({id:m.id,name:m.title,type:m.module_type,points:m.story_points,dev:m.development_people,qa:m.qa_people,perf:m.performance_people,estimatedWeeks:m.estimated_weeks})),roles:Object.fromEntries(roles.rows.map(r=>[r.role_name,r.people_count])),attachments:attachments.rows.map(a=>({id:a.id,name:a.original_name,mimeType:a.mime_type,sizeBytes:a.size_bytes,uploadedAt:a.uploaded_at})),createdAt:proposal.created_at,updatedAt:proposal.updated_at};
}
export async function createProposal(userId,input) { const data=normalizeProposal(input); return withTransaction(async client=>{const row=(await client.query('INSERT INTO proposals(user_id,client_name,budget,planned_team_size,start_date,end_date,client_relationship,proposal_request,backend_story,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[userId,data.clientName,data.budget,data.teamSize,data.startDate,data.endDate,data.relationship,data.request,data.backendStory,data.status])).rows[0];await replaceChildren(client,row.id,data);return getProposal(client,row.id,userId);}); }
export async function updateProposal(userId,id,input) { const data=normalizeProposal(input);return withTransaction(async client=>{const result=await client.query('UPDATE proposals SET client_name=$3,budget=$4,planned_team_size=$5,start_date=$6,end_date=$7,client_relationship=$8,proposal_request=$9,backend_story=$10,status=$11,updated_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id',[id,userId,data.clientName,data.budget,data.teamSize,data.startDate,data.endDate,data.relationship,data.request,data.backendStory,data.status]);if(!result.rowCount)return null;await replaceChildren(client,id,data);return getProposal(client,id,userId);});}
export async function addAttachment(userId,proposalId,file) { const owned=(await pool.query('SELECT 1 FROM proposals WHERE id=$1 AND user_id=$2',[proposalId,userId])).rowCount; if(!owned)return null; const row=(await pool.query('INSERT INTO proposal_attachments(proposal_id,original_name,mime_type,size_bytes,file_data) VALUES($1,$2,$3,$4,$5) RETURNING id,original_name,mime_type,size_bytes,uploaded_at',[proposalId,file.originalname,file.mimetype,file.size,file.buffer])).rows[0];return {id:row.id,name:row.original_name,mimeType:row.mime_type,sizeBytes:row.size_bytes,uploadedAt:row.uploaded_at}; }
export async function getAttachment(userId,proposalId,attachmentId) { const row=(await pool.query('SELECT a.* FROM proposal_attachments a JOIN proposals p ON p.id=a.proposal_id WHERE a.id=$1 AND a.proposal_id=$2 AND p.user_id=$3',[attachmentId,proposalId,userId])).rows[0]; return row||null; }
